import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../', import.meta.url));
const publicDir = path.join(root, 'public');
const outputDir = path.join(publicDir, 'optimized');
await mkdir(outputDir, { recursive: true });

// Keep the originals. Generate static variants so visitors never wait for an
// image transformer to start or download a camera-sized photo for a small card.
async function findImages(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name === 'optimized') continue;
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await findImages(file));
    else if (/\.(jpe?g|png)$/i.test(entry.name)) files.push(file);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

const manifest = {};
const currentFiles = new Set();
let originalBytes = 0;
let cardBytes = 0;
for (const file of await findImages(publicDir)) {
  const input = await readFile(file);
  const metadata = await sharp(input).metadata();
  const { width, height } = metadata.autoOrient;
  const logo = /logo/i.test(path.basename(file));
  const sizes = logo ? [160, 320, 600] : [480, 800, 1280, 1600];
  // Bound portrait height too: a narrow portrait should not decode millions of
  // unused pixels when displayed in a landscape cover.
  const maxWidth = logo ? width : Math.min(width, Math.floor(1920 * width / height));
  const widths = [...new Set(sizes.map((size) => Math.min(size, maxWidth)))];
  const variants = [];
  for (const targetWidth of widths) {
    const quality = logo ? 88 : 72;
    const hash = createHash('sha256').update(input)
      .update(`webp-v1:${sharp.versions.sharp}:${targetWidth}:${quality}:rotate:effort4`)
      .digest('hex').slice(0, 16);
    const name = `${hash}-${targetWidth}.webp`;
    const outputPath = path.join(outputDir, name);
    let output;
    try {
      output = await readFile(outputPath);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
      output = await sharp(input).rotate()
        .resize({ width: targetWidth, withoutEnlargement: true })
        .webp({ quality, effort: 4 }).toBuffer();
      await writeFile(outputPath, output);
    }
    currentFiles.add(name);
    variants.push({ src: `/optimized/${name}`, width: targetWidth });
    if (targetWidth === widths[Math.min(1, widths.length - 1)]) cardBytes += output.length;
  }
  const source = `/${path.relative(publicDir, file).split(path.sep).join('/')}`;
  manifest[source] = {
    src: variants[Math.min(1, variants.length - 1)].src,
    width,
    height,
    srcSet: variants.map((variant) => `${variant.src} ${variant.width}w`).join(', '),
  };
  originalBytes += input.length;
}

await writeFile(path.join(root, 'lib/image-manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
// Remove only obsolete files generated by this script, directly in outputDir.
for (const name of await readdir(outputDir)) {
  if (/^[a-f0-9]{16}-\d+\.webp$/.test(name) && !currentFiles.has(name)) {
    await unlink(path.join(outputDir, name));
  }
}
console.log(`Optimized ${Object.keys(manifest).length} images: ${(originalBytes / 1e6).toFixed(2)} MB originals → ${(cardBytes / 1e6).toFixed(2)} MB card-size WebP (${(100 * (1 - cardBytes / originalBytes)).toFixed(1)}% smaller).`);
