// GENERATED by npm run build:apps-script. Edit lib/impact/core.ts, config.ts or apps-script/adapter.js instead.
const impactConfig = {
    name: 'One person. A new possibility.',
    headline: 'Help one person discover what their experience is worth.',
    description: 'There is someone in your family, workplace, community or network who has spent years learning something valuable. Help them see where that experience could take them.',
    contactEmail: 'eshietsfoundation@gmail.com',
    milestones: [1, 5, 10, 25, 50, 100],
    professions: ['Teacher', 'Lecturer', 'Banker', 'Accountant', 'Civil Servant', 'Healthcare Professional', 'Business Owner', 'Entrepreneur', 'Creative', 'Artisan', 'Engineer', 'Lawyer', 'Sales Professional', 'Marketing Professional', 'Other'],
    experienceRanges: ['Less than 3', '3–5 years', '6–10 years', '11–15 years', '16–20 years', '20+ years', "I don’t know yet"],
    outsideIncome: ['Yes', 'No', 'Not yet'],
    intentIncome: ['Yes', 'No', "I’m not sure"],
    goals: ['Where my experience is valuable', 'How to package what I know', 'Who could pay for my knowledge', 'How to build an additional income stream from my expertise', 'How to position myself professionally', "I’m still figuring it out"],
    missions: ['Find one teacher with more than 10 years of experience.', 'Think of someone in your family who has worked in the same profession for more than five years.', 'Call someone who taught you something that still helps you today.', 'Ask an experienced colleague: “Have you ever earned from what you know outside your normal job?”'],
    shareText: 'You know more than you might think. Take a moment to discover what your experience could become with EITDA.',
    wallPageSize: 24,
    statsRefreshMs: 60000,
    privacyVersion: '2026-09-10',
};
function currentMission(now = new Date()) {
    return impactConfig.missions[Math.floor(now.getTime() / 604800000) % impactConfig.missions.length];
}

class ImpactError extends Error {
    constructor(message, status = 400) { super(message); this.status = status; }
}
const schemas = {
    Advocates: ['advocate_id', 'impact_code', 'first_name', 'last_name', 'email', 'phone', 'city', 'country', 'twitter', 'linkedin', 'instagram', 'profession_person_in_mind', 'experience_range_person_in_mind', 'outside_income_answer', 'date_joined', 'status', 'total_people_reached', 'current_milestone', 'submission_id', 'submission_hash', 'submission_secret_hash', 'dashboard_token_hash', 'privacy_consent_at', 'privacy_version', 'recognition_consent', 'possible_duplicate'],
    People: ['person_id', 'advocate_code', 'first_name', 'profession', 'years_experience', 'outside_income', 'known_for', 'discovery_goal', 'email', 'phone', 'city', 'country', 'registration_status', 'ticket_status', 'public_display_consent', 'date_added', 'submission_id', 'submission_hash', 'submission_secret_hash', 'consent_token_hash', 'privacy_consent_at', 'privacy_version', 'person_number', 'featured', 'story_collected', 'outcome_recorded'],
    Events: ['event_id', 'timestamp', 'event_type', 'advocate_code', 'person_id', 'metadata', 'submission_id'],
    Milestones: ['advocate_code', 'milestone', 'date_achieved', 'notification_status'],
    PublicImpact: ['public_id', 'first_name_or_initial', 'profession', 'years_experience', 'advocate_first_name', 'date_added', 'featured'],
};
function emptyState() { return { Advocates: [], People: [], Events: [], Milestones: [], PublicImpact: [] }; }
function textField(value, label, max, required = true) {
    if (value == null && !required)
        return '';
    if (typeof value !== 'string')
        throw new ImpactError(`Please enter ${label}.`);
    const result = value.normalize('NFKC').replace(/[\u0000-\u001f\u007f-\u009f<>]/g, '').trim();
    if ((required && !result) || result.length > max)
        throw new ImpactError(`Please check ${label} (up to ${max} characters).`);
    return result;
}
function option(value, choices, label) {
    if (typeof value !== 'string' || !choices.includes(value))
        throw new ImpactError(`Please choose ${label}.`);
    return value;
}
function email(value, required) {
    const result = textField(value, 'your email', 254, required).toLowerCase();
    if (result && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result))
        throw new ImpactError('Please check your email address.');
    return result;
}
function phone(value, required) {
    const result = textField(value, 'your phone number', 30, required);
    if (result && (!/^[+\d\s().-]+$/.test(result) || result.replace(/\D/g, '').length < 7))
        throw new ImpactError('Please check your phone number.');
    return result;
}
function bool(value, label) {
    if (typeof value !== 'boolean')
        throw new ImpactError(`Please check ${label}.`);
    return value;
}
const consented = (value) => value === true || value === 'TRUE';
function sheetSafe(value) {
    return typeof value === 'string' && /^[\s]*[=+\-@*'\t\r]/.test(value) ? `'${value}` : value;
}
function safeEqual(a, b) {
    let mismatch = a.length ^ b.length;
    for (let i = 0; i < Math.max(a.length, b.length); i++)
        mismatch |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
    return mismatch === 0;
}
function activePeople(state) { return state.People.filter(p => p.registration_status === 'experience_completed'); }
function advocateFor(state, code, required = true) {
    const advocate = state.Advocates.find(a => a.impact_code === code && a.status === 'active');
    if (required && !advocate)
        throw new ImpactError('This impact link is unavailable. Ask the person who shared it for a new link.', 404);
    return advocate;
}
function requireToken(row, token, field, runtime) {
    if (!row || typeof token !== 'string' || !/^[a-f0-9]{64}$/.test(token) || !safeEqual(String(row[field]), runtime.hash(token))) {
        throw new ImpactError('Use your private access link to open this page.', 401);
    }
    return row;
}
function event(state, runtime, type, code = '', person = '', metadata = {}, key = runtime.id()) {
    const eventId = runtime.hash(`event:${key}`).slice(0, 32);
    if (!state.Events.some(e => e.event_id === eventId))
        state.Events.push({ event_id: eventId, timestamp: runtime.now(), event_type: type, advocate_code: code, person_id: person, metadata: JSON.stringify(metadata), submission_id: key });
}
function reconcile(state, runtime) {
    const people = activePeople(state);
    for (const advocate of state.Advocates) {
        const reached = people.filter(p => p.advocate_code === advocate.impact_code).length;
        advocate.total_people_reached = reached;
        advocate.current_milestone = Math.max(0, ...impactConfig.milestones.filter(n => n <= reached));
        for (const milestone of impactConfig.milestones.filter(n => n <= reached)) {
            if (!state.Milestones.some(m => m.advocate_code === advocate.impact_code && Number(m.milestone) === milestone)) {
                state.Milestones.push({ advocate_code: advocate.impact_code, milestone, date_achieved: runtime.now(), notification_status: 'not_sent' });
                event(state, runtime, 'milestone_reached', String(advocate.impact_code), '', { milestone }, `${advocate.impact_code}:${milestone}`);
            }
        }
    }
    state.PublicImpact = people.map(p => publicPerson(state, p));
}
function publicPerson(state, person) {
    const visible = consented(person.public_display_consent);
    const advocate = advocateFor(state, person.advocate_code, false);
    return {
        public_id: person.person_id,
        first_name_or_initial: visible ? person.first_name : '',
        profession: person.profession,
        years_experience: person.years_experience,
        advocate_first_name: visible && advocate && consented(advocate.recognition_consent) ? advocate.first_name : '',
        date_added: person.date_added,
        featured: visible && consented(person.featured),
    };
}
function campaignStats(state) {
    const people = activePeople(state);
    return { people: people.length, combined_years: people.reduce((sum, p) => sum + (typeof p.years_experience === 'number' && Number.isFinite(p.years_experience) ? p.years_experience : 0), 0) };
}
function pageOf(items, payload) {
    const offset = payload.offset == null ? 0 : Number(payload.offset);
    const limit = payload.limit == null ? impactConfig.wallPageSize : Number(payload.limit);
    if (!Number.isInteger(offset) || offset < 0 || !Number.isInteger(limit) || limit < 1 || limit > 48)
        throw new ImpactError('Please check the page requested.');
    return { items: items.slice(offset, offset + limit), next_offset: offset + limit < items.length ? offset + limit : null, total: items.length };
}
function submission(payload, runtime) {
    const id = textField(payload.submission_id, 'the submission ID', 80);
    const secret = textField(payload.submission_secret, 'the submission key', 80);
    if (!/^[a-f0-9-]{32,80}$/.test(id) || !/^[a-f0-9]{64}$/.test(secret))
        throw new ImpactError('Please refresh the form and try again.');
    return { id, secret, secretHash: runtime.hash(secret) };
}
function retryRecord(rows, id, secretHash, hash) {
    const old = rows.find(r => r.submission_id === id);
    if (old && (!safeEqual(String(old.submission_secret_hash), secretHash) || !safeEqual(String(old.submission_hash), hash)))
        throw new ImpactError('This submission was already used with different details. Start a new form.', 409);
    return old;
}
function perform(state, action, payload, runtime) {
    if (action === 'getCampaignStats')
        return campaignStats(state);
    if (action === 'getPublicImpact')
        return pageOf(activePeople(state).slice().reverse().map(p => publicPerson(state, p)), payload);
    if (action === 'getRecognition')
        return { items: state.Advocates.filter(a => a.status === 'active' && consented(a.recognition_consent)).map(a => ({ first_name: a.first_name, people: activePeople(state).filter(p => p.advocate_code === a.impact_code).length })).filter(a => a.people > 0).slice(0, 6) };
    if (action === 'getAdvocate') {
        const a = advocateFor(state, payload.code);
        return { code: a.impact_code, first_name: consented(a.recognition_consent) ? a.first_name : '', active: true };
    }
    if (action === 'getAdvocateImpact') {
        const a = requireToken(advocateFor(state, payload.code, false), payload.token, 'dashboard_token_hash', runtime);
        const people = activePeople(state).filter(p => p.advocate_code === a.impact_code);
        const reached = people.length;
        return { code: a.impact_code, first_name: a.first_name, people: reached, milestone: Math.max(0, ...impactConfig.milestones.filter(n => n <= reached)), milestones: state.Milestones.filter(m => m.advocate_code === a.impact_code).map(m => ({ milestone: m.milestone, date_achieved: m.date_achieved })), ...pageOf(people.slice().reverse().map(p => ({ ...publicPerson(state, p), status: ['confirmed', 'attended'].includes(String(p.ticket_status)) ? 'Coming to EITDA' : 'Experience completed' })), payload) };
    }
    if (action === 'getPerson') {
        const p = requireToken(state.People.find(p => p.person_id === payload.person_id), payload.token, 'consent_token_hash', runtime);
        return { person_id: p.person_id, first_name: p.first_name, public_display_consent: consented(p.public_display_consent), ticket_status: p.ticket_status };
    }
    if (action === 'createAdvocate') {
        const sub = submission(payload, runtime);
        if (payload.privacy_consent !== true || payload.commitment !== true)
            throw new ImpactError('Please confirm both required checkboxes.');
        const linkedin = textField(payload.linkedin, 'your LinkedIn profile', 240, false);
        if (linkedin && !/^https:\/\/(www\.)?linkedin\.com\/(in|company)\/[a-zA-Z0-9%_-]+\/?$/.test(linkedin))
            throw new ImpactError('Use a full LinkedIn profile link.');
        const fields = {
            first_name: textField(payload.first_name, 'your first name', 60), last_name: textField(payload.last_name, 'your last name', 60), email: email(payload.email, true), phone: phone(payload.phone, true), city: textField(payload.city, 'your city', 80), country: textField(payload.country, 'your country', 80), twitter: textField(payload.twitter, 'your X username', 60, false), linkedin, instagram: textField(payload.instagram, 'your Instagram username', 60, false),
            profession_person_in_mind: option(payload.profession_person_in_mind, impactConfig.professions, 'a profession'), experience_range_person_in_mind: option(payload.experience_range_person_in_mind, impactConfig.experienceRanges, 'an experience range'), outside_income_answer: option(payload.outside_income_answer, impactConfig.intentIncome, 'an answer'), recognition_consent: bool(payload.recognition_consent ?? false, 'recognition consent'),
        };
        const hash = runtime.hash(JSON.stringify(fields));
        let advocate = retryRecord(state.Advocates, sub.id, sub.secretHash, hash);
        const token = runtime.token(`dashboard:${sub.id}:${sub.secret}`);
        if (!advocate) {
            let code = '';
            for (let i = 0; i < 20; i++) {
                code = `ONE${runtime.id().replace(/-/g, '').slice(0, 8).toUpperCase()}`;
                if (!state.Advocates.some(a => a.impact_code === code))
                    break;
                code = '';
            }
            if (!code)
                throw new ImpactError('Please try again in a moment.', 503);
            advocate = { ...fields, advocate_id: runtime.id(), impact_code: code, date_joined: runtime.now(), status: 'active', total_people_reached: 0, current_milestone: 0, submission_id: sub.id, submission_hash: hash, submission_secret_hash: sub.secretHash, dashboard_token_hash: runtime.hash(token), privacy_consent_at: runtime.now(), privacy_version: impactConfig.privacyVersion, possible_duplicate: state.Advocates.some(a => a.email === fields.email) };
            state.Advocates.push(advocate);
        }
        event(state, runtime, 'advocate_created', String(advocate.impact_code), '', {}, `advocate:${sub.id}`);
        reconcile(state, runtime);
        return { code: advocate.impact_code, first_name: advocate.first_name, dashboard_token: token };
    }
    if (action === 'createPerson') {
        const sub = submission(payload, runtime);
        if (payload.privacy_consent !== true)
            throw new ImpactError('Please agree to the privacy notice.');
        const code = textField(payload.advocate_code ?? '', 'the impact code', 32, false).toUpperCase();
        if (code)
            advocateFor(state, code);
        if (typeof payload.years_experience !== 'number' || !Number.isInteger(payload.years_experience) || payload.years_experience < 0 || payload.years_experience > 80)
            throw new ImpactError('Enter your actual years of experience, from 0 to 80.');
        const fields = { advocate_code: code, first_name: textField(payload.first_name, 'your first name', 60), profession: option(payload.profession, impactConfig.professions, 'your profession'), years_experience: payload.years_experience, outside_income: option(payload.outside_income, impactConfig.outsideIncome, 'an answer'), known_for: textField(payload.known_for, 'what people ask you for help with', 500), discovery_goal: option(payload.discovery_goal, impactConfig.goals, 'what you want to understand'), email: email(payload.email, false), phone: phone(payload.phone, false), city: textField(payload.city, 'your city', 80, false), country: textField(payload.country, 'your country', 80, false), public_display_consent: bool(payload.public_display_consent ?? false, 'wall consent') };
        const hash = runtime.hash(JSON.stringify(fields));
        let person = retryRecord(state.People, sub.id, sub.secretHash, hash);
        const token = runtime.token(`consent:${sub.id}:${sub.secret}`);
        if (!person) {
            person = { ...fields, person_id: runtime.id(), registration_status: 'experience_completed', ticket_status: 'not_started', date_added: runtime.now(), submission_id: sub.id, submission_hash: hash, submission_secret_hash: sub.secretHash, consent_token_hash: runtime.hash(token), privacy_consent_at: runtime.now(), privacy_version: impactConfig.privacyVersion, person_number: Math.max(0, ...state.People.map(p => Number(p.person_number) || 0)) + 1, featured: false, story_collected: false, outcome_recorded: false };
            state.People.push(person);
        }
        event(state, runtime, 'experience_completed', code, String(person.person_id), {}, `person:${sub.id}`);
        reconcile(state, runtime);
        return { person_id: person.person_id, person_number: person.person_number, first_name: person.first_name, profession: person.profession, years_experience: person.years_experience, consent_token: token, public_display_consent: consented(person.public_display_consent), stats: campaignStats(state) };
    }
    if (action === 'updateConsent') {
        const p = requireToken(state.People.find(p => p.person_id === payload.person_id), payload.token, 'consent_token_hash', runtime);
        p.public_display_consent = bool(payload.public_display_consent, 'wall consent');
        event(state, runtime, 'consent_updated', String(p.advocate_code), String(p.person_id), { public_display_consent: p.public_display_consent });
        reconcile(state, runtime);
        return { public_display_consent: p.public_display_consent };
    }
    if (action === 'trackEvent') {
        const type = option(payload.event_type, ['impact_link_opened', 'experience_started', 'share_clicked', 'ticket_clicked'], 'an activity');
        const id = textField(payload.submission_id, 'the activity ID', 80);
        if (!/^[a-f0-9-]{32,80}$/.test(id))
            throw new ImpactError('Invalid activity.');
        let code = textField(payload.advocate_code ?? '', 'the impact code', 32, false).toUpperCase();
        let personId = '';
        const metadata = {};
        if (type === 'ticket_clicked') {
            const p = requireToken(state.People.find(p => p.person_id === payload.person_id), payload.token, 'consent_token_hash', runtime);
            if (p.ticket_status === 'not_started')
                p.ticket_status = 'clicked';
            personId = String(p.person_id);
            code = String(p.advocate_code);
            metadata.ticket = option(payload.ticket, ['general', 'vip'], 'a ticket');
        }
        else if (code)
            advocateFor(state, code);
        if (type === 'share_clicked')
            metadata.channel = option(payload.channel, ['copy', 'whatsapp', 'x', 'linkedin', 'facebook', 'download', 'native'], 'a share option');
        event(state, runtime, type, code, personId, metadata, `activity:${id}`);
        return { recorded: true };
    }
    throw new ImpactError('This action is not available.', 404);
}

// Runtime adapter appended to the shared, tested validation engine by build-apps-script.mjs.
// This source is not loaded by the website. Deploy generated Code.gs to Apps Script.
function property_(name) {
  var value = PropertiesService.getScriptProperties().getProperty(name);
  if (!value) throw new ImpactError('Campaign configuration needs attention.', 503);
  return value;
}
function hex_(bytes) { return bytes.map(function(b) { return ('0' + ((b + 256) % 256).toString(16)).slice(-2); }).join(''); }
function runtime_() {
  var secret = property_('TOKEN_SECRET');
  if (!/^[a-f0-9]{64}$/.test(secret)) throw new ImpactError('Campaign configuration needs attention.', 503);
  return {
    now: function() { return new Date().toISOString(); },
    id: function() { return Utilities.getUuid(); },
    hash: function(value) { return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, value, Utilities.Charset.UTF_8)); },
    token: function(value) { return hex_(Utilities.computeHmacSha256Signature(value, secret, Utilities.Charset.UTF_8)); }
  };
}
function spreadsheet_() { return SpreadsheetApp.openById(property_('SPREADSHEET_ID')); }
function loadState_(spreadsheet) {
  var state = emptyState();
  Object.keys(schemas).forEach(function(name) {
    var sheet = spreadsheet.getSheetByName(name);
    if (!sheet) throw new ImpactError('Run setupCampaign in Apps Script first.', 503);
    var headers = sheet.getRange(1, 1, 1, schemas[name].length).getValues()[0];
    if (headers.join('|') !== schemas[name].join('|')) throw new ImpactError('Campaign sheet headers have changed. Ask the team to check setup.', 503);
    if (sheet.getLastRow() < 2) return;
    state[name] = sheet.getRange(2, 1, sheet.getLastRow() - 1, headers.length).getValues().filter(function(values) { return values[0] !== ''; }).map(function(values) {
      var row = {};
      headers.forEach(function(key, index) { var value = values[index]; row[key] = value instanceof Date ? value.toISOString() : value; });
      return row;
    });
  });
  return state;
}
function saveState_(spreadsheet, before, state) {
  // Primary records first. Retries recover from a partial write using submission
  // IDs and deterministic credentials, and reconcile derived counters/events.
  ['People','Advocates','Events','Milestones','PublicImpact'].forEach(function(name) {
    var sheet = spreadsheet.getSheetByName(name);
    var columns = schemas[name];
    var rows = state[name];
    var old = before[name];
    if (sheet.getMaxRows() < rows.length + 1) sheet.insertRowsAfter(sheet.getMaxRows(), rows.length + 1 - sheet.getMaxRows());
    for (var i = 0; i < Math.min(old.length, rows.length); i++) {
      if (JSON.stringify(old[i]) !== JSON.stringify(rows[i])) {
        if (name === 'Events') throw new Error('Events are append-only.');
        sheet.getRange(i + 2, 1, 1, columns.length).setValues([columns.map(function(key) { return sheetSafe(rows[i][key] === undefined ? '' : rows[i][key]); })]);
      }
    }
    if (rows.length > old.length) {
      var added = rows.slice(old.length).map(function(row) { return columns.map(function(key) { return sheetSafe(row[key] === undefined ? '' : row[key]); }); });
      sheet.getRange(old.length + 2, 1, added.length, columns.length).setValues(added);
    }
    if (old.length > rows.length && name === 'PublicImpact') sheet.getRange(rows.length + 2, 1, old.length - rows.length, columns.length).clearContent();
  });
  SpreadsheetApp.flush();
}
function rate_(key, limit, seconds) {
  var cache = CacheService.getScriptCache();
  var count = Number(cache.get(key) || 0);
  if (count >= limit) throw new ImpactError('Please wait a few minutes before trying again.', 429);
  cache.put(key, String(count + 1), seconds);
}
function json_(value) { return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON); }
function response_(action, payload, clientKey, publicOnly) {
  var lock = LockService.getScriptLock();
  var acquired = false;
  try {
    acquired = lock.tryLock(5000);
    if (!acquired) throw new ImpactError('The campaign is busy. Please try again shortly.', 503);
    var reads = ['getCampaignStats','getPublicImpact','getAdvocate','getRecognition'];
    if (publicOnly && reads.indexOf(action) === -1) throw new ImpactError('Use the secure website form for this action.', 401);
    var read = reads.indexOf(action) !== -1 || action === 'getAdvocateImpact' || action === 'getPerson';
    rate_('global:' + (read ? 'read' : 'write'), read ? 1500 : 600, 600);
    if (!publicOnly) rate_('client:' + clientKey + ':' + (read ? 'read' : 'write'), read ? 180 : 40, 600);
    if (action === 'getCampaignStats') {
      var cached = CacheService.getScriptCache().get('campaign-stats');
      if (cached) return json_({success:true, data:JSON.parse(cached)});
    }
    var spreadsheet = spreadsheet_();
    var state = loadState_(spreadsheet);
    var before = JSON.parse(JSON.stringify(state));
    var result = perform(state, action, payload, runtime_());
    if (!read) {
      saveState_(spreadsheet, before, state);
      CacheService.getScriptCache().remove('campaign-stats');
    }
    if (action === 'getCampaignStats') CacheService.getScriptCache().put('campaign-stats', JSON.stringify(result), 30);
    return json_({success:true, data:result});
  } catch (error) {
    return json_({success:false, error:error instanceof ImpactError ? error.message : 'We couldn’t save this right now. Please try again.', status:error instanceof ImpactError ? error.status : 503});
  } finally { if (acquired) lock.releaseLock(); }
}
function doGet(e) {
  var params = e && e.parameter || {};
  return response_(String(params.action || ''), params, 'public', true);
}
function doPost(e) {
  try {
    var raw = e && e.postData && e.postData.contents || '';
    if (raw.length > 20000) throw new ImpactError('This submission is too large.');
    var body = JSON.parse(raw);
    var secret = property_('API_SECRET');
    if (!/^[a-f0-9]{64}$/.test(secret) || typeof body.api_secret !== 'string' || !safeEqual(secret, body.api_secret)) throw new ImpactError('Use the secure website form for this action.', 401);
    if (!/^[a-f0-9]{64}$/.test(body.client_key || '') || !body.payload || typeof body.payload !== 'object' || Array.isArray(body.payload)) throw new ImpactError('Invalid submission.');
    return response_(String(body.action || ''), body.payload, body.client_key, false);
  } catch (error) {
    return json_({success:false, error:error instanceof ImpactError ? error.message : 'Invalid submission.', status:error instanceof ImpactError ? error.status : 400});
  }
}
function setupCampaign() {
  var spreadsheet = spreadsheet_();
  Object.keys(schemas).forEach(function(name) {
    var sheet = spreadsheet.getSheetByName(name) || spreadsheet.insertSheet(name);
    if (sheet.getLastRow() === 0) {
      if (sheet.getMaxColumns() < schemas[name].length) sheet.insertColumnsAfter(sheet.getMaxColumns(), schemas[name].length - sheet.getMaxColumns());
      sheet.getRange(1, 1, 1, schemas[name].length).setValues([schemas[name]]).setFontWeight('bold').setBackground('#0731b5').setFontColor('#ffffff');
      sheet.setFrozenRows(1);
    }
  });
  loadState_(spreadsheet); // Fail clearly instead of silently replacing changed headers.
}
function syncCampaign() {
  var lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    var spreadsheet = spreadsheet_();
    var state = loadState_(spreadsheet);
    var before = JSON.parse(JSON.stringify(state));
    var runtime = runtime_();
    state.People.forEach(function(p) {
      if (p.ticket_status === 'confirmed' || p.ticket_status === 'attended') event(state, runtime, p.ticket_status === 'confirmed' ? 'ticket_confirmed' : 'attended', String(p.advocate_code), String(p.person_id), {source:'team_sheet_update'}, 'manual:' + p.person_id + ':' + p.ticket_status);
    });
    reconcile(state, runtime);
    saveState_(spreadsheet, before, state);
    CacheService.getScriptCache().remove('campaign-stats');
  } finally { lock.releaseLock(); }
}
function campaignEdited(e) {
  if (e && e.range && ['People','Advocates'].indexOf(e.range.getSheet().getName()) !== -1) syncCampaign();
}
function installCampaignTrigger() {
  ScriptApp.getProjectTriggers().forEach(function(trigger) { if (trigger.getHandlerFunction() === 'campaignEdited') ScriptApp.deleteTrigger(trigger); });
  ScriptApp.newTrigger('campaignEdited').forSpreadsheet(property_('SPREADSHEET_ID')).onEdit().create();
}
function onOpen() {
  SpreadsheetApp.getUi().createMenu('EITDA campaign').addItem('Check / create tabs', 'setupCampaign').addItem('Refresh counts, wall and ticket events', 'syncCampaign').addToUi();
}
